name = "caprea"
type = "javascript"
account_id = "72a3e474fee1d0bb856f4077d70f2309"
workers_dev = true
compatibility_date = "2021-12-21"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
